error_handling:
  alert_on_critical: true
  enable_detailed_logging: true
  max_error_history: 1000
  max_retry_attempts: 3
  retry_delays:
  - 1
  - 2
  - 4
gemini:
  max_tokens: 4096
  model: gemini-pro
  retry_attempts: 3
  temperature: 0.1
  timeout: 30
logging:
  backup_count: 5
  enable_json: false
  file_path: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
odoo:
  retry_attempts: 3
  timeout: 30
  verify_ssl: true
performance:
  enable_monitoring: true
  error_rate_threshold: 0.1
  high_cpu_threshold: 80.0
  high_memory_threshold: 85.0
  max_metrics_history: 10000
  monitoring_interval: 30.0
  slow_operation_threshold: 5.0
security:
  allowed_file_types:
  - .pdf
  - .png
  - .jpg
  - .jpeg
  - .txt
  - .csv
  enable_audit_logging: true
  enable_input_validation: true
  enable_rate_limiting: true
  max_file_size: 52428800
  max_requests_per_minute: 60
streamlit:
  debug: false
  host: localhost
  max_upload_size: 200
  port: 8501
